version: "3.7"
services: 
    db:
        image: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lesson
        volumes: 
            - ./pgdata:/var/lib/postgres/data
        ports: 
            - '5432:5432'
    
    lesson:
        image: frametee29/lesson:dev
        restart: always
        container_name: lesson
        ports:
            - '3000:3000'