version: "3.3"
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lesson
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"

  lesson:
    image: frametee29/lesson:dev
    restart: always
    container_name: lesson
    ports:
      - "3000:3000"
    links:
      - db
    depends_on: 
      - db
    environment:
      WAIT_HOSTS: db:5432

